
services:
  base:
    image: ros2_kilted_eta:latest
    container_name: ros2_kilted_eta_base_container
    restart: unless-stopped

    network_mode: host
    ipc: host
    privileged: true

    environment:
      DISPLAY: ${DISPLAY}
      XAUTHORITY: /tmp/.docker.xauth
      QT_X11_NO_MITSHM: "1"

    volumes:
      # - ./20_ROS/src:/home/admin/ros_ws/mount
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw

    devices:
      - /dev/dri:/dev/dri

    command: ["tail", "-f", "/dev/null"]

    stdin_open: true
    tty: true


  db:
    image: postgres:18.4
    container_name: postgres_db_container
    restart: unless-stopped

    networks:
      - eta_network

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "1"
      POSTGRES_DB: robotdata

    volumes:
      - ../40_DB/postgres_data:/var/lib/postgresql
      - ../40_DB/filebrowser_data/init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "5432:5432"


  db_gui:
    image: dpage/pgadmin4:latest
    container_name: postgres_db_gui_container
    restart: unless-stopped

    networks:
      - eta_network

    environment:
      PGADMIN_DEFAULT_EMAIL: fabian.nachbur@eta.ch
      PGADMIN_DEFAULT_PASSWORD: "1"

    ports:
      - "8080:80"

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser_container
    restart: unless-stopped

    networks:
      - eta_network

    environment:
      PUID: 1000
      PGID: 1000
      UMASK_SET: 022

    volumes:
      # - ./filebrowser_data:/srv

      - ../40_DB/filebrowser_data:/database
      - ../40_DB/filebrowser_config:/config

    ports:
      - "8081:80"

networks:
  eta_network:
    driver: bridge
