services:

  interface:
    image: ros2_kilted_eta_interface:latest
    container_name: eta_interface_container
    networks:
      - eta_network
    ipc: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    stdin_open: true
    tty: true

  eta:
    image: ros2_kilted_eta_base:latest
    container_name: eta_base_container
    networks:
      - eta_network
    ipc: host
    privileged: true
    stdin_open: true
    tty: true

  rmf:
    image: ros2_kilted_eta_rmf:latest
    container_name: eta_rmf_container
    networks:
      - eta_network
    ipc: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    stdin_open: true
    tty: true

  gz:
    image: ros2_kilted_eta_gz:latest
    container_name: eta_gz_container
    networks:
      - eta_network
    ipc: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    stdin_open: true
    tty: true

  db:
    image: postgres:18.4
    container_name: postgres_db_container
    restart: unless-stopped
    networks:
      - eta_network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: robotdata
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./40_DB/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  db_gui:
    image: dpage/pgadmin4:latest
    container_name: postgres_db_gui_container
    restart: unless-stopped
    networks:
      - eta_network
    environment:
      PGADMIN_DEFAULT_EMAIL: fabian.nachbur@eta.ch
      PGADMIN_DEFAULT_PASSWORD: 1
    ports:
      - "8080:80"


networks:
  eta_network:
    driver: bridge