services:

  interface:
    image: orka375/eta_tc_ros2_itf:latest
    container_name: interface_container
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    stdin_open: true
    tty: true
  eta:
    image: orka375/ros2_kilted_eta:latest
    container_name: eta_container
    network_mode: host
    ipc: host
    privileged: true
    stdin_open: true
    tty: true

  fleet:
    image: orka375/ros2_kilted_eta_fleet:latest
    container_name: eta_fleet_container
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    stdin_open: true
    tty: true

  gazebo:
    image: orka375/ros2_kilted_eta_gz:latest
    container_name: eta_gz_container
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    stdin_open: true
    tty: true

  db: 
    image: postgres:18.4
    container_name: postgres_db_container
    restart: unless-stopped
    # network_mode: host
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: robotdata
    volumes:
      - ./postgres_data:/var/lib/postgresql
      - ./40_DB/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
   
  db_gui:
    image: dpage/pgadmin4:latest

    container_name: postgres_db_gui_container

    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: fabian.nachbur@eta.ch
      PGADMIN_DEFAULT_PASSWORD: 1

    ports:
      - "8080:80"


volumes:

  postgres_data: