<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_ROS2Camera" Id="{f1b2c3d4-5557-5555-5555-555555555555}">
	<Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK FB_ROS2Camera EXTENDS FB_Camera
VAR
	// ROS2 Camera specific properties
END_VAR
]]>
	</Declaration>
	<Implementation>
	  <ST><![CDATA[// ROS2 Camera implementation
]]>
	  </ST>
	</Implementation>
  </POU>
</TcPlcObject>
