<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_SetDO" Id="{f1b2c3d4-7775-7777-7777-777777777777}">
	<Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK FB_SetDO EXTENDS FB_BaseAction
VAR
	// SetDO specific properties
	outputId : INT;
	value : BOOL;
END_VAR
]]>
	</Declaration>
	<Implementation>
	  <ST><![CDATA[// SetDO implementation
]]>
	  </ST>
	</Implementation>
  </POU>
</TcPlcObject>
