<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_TwinCATCamera" Id="{f1b2c3d4-5556-5555-5555-555555555555}">
	<Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK FB_TwinCATCamera EXTENDS FB_Camera
VAR
	// TwinCAT Camera specific properties
END_VAR
]]>
	</Declaration>
	<Implementation>
	  <ST><![CDATA[// TwinCAT Camera implementation
]]>
	  </ST>
	</Implementation>
  </POU>
</TcPlcObject>
