<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="UR5" Id="{7b4b5083-e79a-4c10-9e6c-511e517d77af}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK UR5 IMPLEMENTS ITF_6AxisRobot
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="activate" Id="{e1d9a52c-851b-42f3-894f-7e3c96e56872}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD activate : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="cleanup" Id="{4a53a1b4-96cf-4c35-9d3d-22cef0748b8b}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD cleanup : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="configure" Id="{d3b60e10-326a-4e20-9a3c-e3dda19d01c0}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD configure : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="create" Id="{b605b126-44ea-476e-89a1-7bb411313df1}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD create : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="currentFrame" Id="{a021991b-da56-401c-b9f8-9afb80b6cc93}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY currentFrame : stFrame
]]></Declaration>
      <Get Name="Get" Id="{7743789c-bfc9-422c-8ce4-f03cd3cadb38}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{dc781d27-f0b9-41bf-9723-fece521d312c}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Property Name="currentFrameID" Id="{92b45ae8-725d-45b2-b872-2a620ec24ab8}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY currentFrameID : UINT
]]></Declaration>
      <Get Name="Get" Id="{4a625290-c57d-4ba3-b991-759b0cc912af}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="currentTool" Id="{fa9771a5-ffeb-49ad-baa2-4e99ec375cec}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY currentTool : stTool
]]></Declaration>
      <Get Name="Get" Id="{84c16485-caad-40f8-acad-04df5c6d4278}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{6973955d-4e63-4b4e-8a95-2b8183a603ee}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Method Name="deactivate" Id="{ed06cd85-bc42-4e9a-91cc-1628bf3b53f9}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD deactivate : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="destroy" Id="{c40419fc-9189-4dd4-97ae-761eaac26aa3}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD destroy : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="disable" Id="{61d5b48d-5c80-4312-a78b-5402742ee178}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD disable : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="disableVelocityOverride" Id="{eafd5b96-7586-43d7-96db-a8e956f3ba56}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD disableVelocityOverride : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="enable" Id="{393b415a-2ad2-4818-9a04-f565e2c46cfe}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD enable : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="enableVelocityOverride" Id="{1418bf88-3542-4c00-98bc-fc6c2ed94c84}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD enableVelocityOverride : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="estop" Id="{216e4803-8f80-4ce0-9336-bbcacabd9564}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD estop : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Home" Id="{cc00f5d5-5518-4792-a959-10dbf9c99593}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD Home : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="ID" Id="{1dbcccc2-c9c3-45a8-9653-5692b1d4c14c}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD ID : UINT
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="isInCollision" Id="{b28889d8-063a-47b9-84df-e8e91e3c6fae}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY isInCollision : BOOL
]]></Declaration>
      <Get Name="Get" Id="{34338825-c09e-48d4-bd36-14932d5a1ac0}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="isInHomePosition" Id="{f971dc03-34a7-4c06-a90a-bd6cafbd79df}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY isInHomePosition : BOOL
]]></Declaration>
      <Get Name="Get" Id="{37951abb-77ce-47dd-a9b9-61b766433f54}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="jointPosition" Id="{f814761f-2ca5-4581-86e5-6ff8c07a8801}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY jointPosition : stJointPosition6
]]></Declaration>
      <Get Name="Get" Id="{db162c65-9a1d-4f46-b87e-fcb3a78549b1}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="jointVelocity" Id="{69420199-98a5-4f30-b1e8-13db04017daa}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY jointVelocity : stJointPosition6
]]></Declaration>
      <Get Name="Get" Id="{8477f9a5-16ce-4dd9-a5af-d2bd83c8094b}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="M_AUTO" Id="{fc63a1fb-d8f7-4b97-ad19-67c99ba95b61}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD M_AUTO : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_MAN" Id="{55d71ac3-c1bf-4f72-bb9b-4c8aed32a1c5}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD M_MAN : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="MC_ChangeSpeedOverride" Id="{2e5b6437-ddae-4c5a-9d4a-9e258707bf4d}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD MC_ChangeSpeedOverride : INT
VAR_INPUT
	factor	: REAL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="MC_MoveAxesAbsolute" Id="{06b1e0db-8923-4bd6-b76b-273f56d9b898}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD MC_MoveAxesAbsolute : BOOL
VAR_INPUT
	target	: Target;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="MC_MoveAxesRelative" Id="{664e3a69-1a1e-44da-8b41-c67130c08d6e}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD MC_MoveAxesRelative : BOOL
VAR_INPUT
	axes	: ARRAY [1..6] OF Axis;
	offsets	: ARRAY [1..6] OF REAL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="MC_MoveLinearAbsolute" Id="{5204bccd-69b7-497c-ad3c-b5723ae586c1}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD MC_MoveLinearAbsolute : BOOL
VAR_INPUT
	target	: Target;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="MC_ReadActualVelocity" Id="{7a54b305-2af0-4e73-a2c6-4df2faae69e0}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD MC_ReadActualVelocity : stPose
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="MC_ReadAnalogInput" Id="{f685b253-261c-4818-ab8e-a89f5da5e34b}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD MC_ReadAnalogInput : LREAL
VAR_INPUT
	input	: INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="MC_ReadDigitalInput" Id="{900349a5-235a-40e6-99ff-58006d3aedbf}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD MC_ReadDigitalInput : BOOL
VAR_INPUT
	input	: INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="MC_SetDigitalOutput" Id="{f98ee055-6f2b-4bbc-a038-2fcfa522f345}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD MC_SetDigitalOutput : BOOL
VAR_INPUT
	output	: INT;
	value	: BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="MC_SetOperationMode" Id="{447f3588-d5a5-48c3-b8e9-2584ee98e5d4}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD MC_SetOperationMode : BOOL
VAR_INPUT
	mode	: eMode;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="name" Id="{e935019a-0018-47d2-aeb8-eb645d550c83}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY name : STRING
]]></Declaration>
      <Get Name="Get" Id="{e56b6b75-248b-4f14-a436-ddd5f8094dfd}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="onActivate" Id="{6dd729e8-45c5-48de-83a4-a757dd15b57d}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD onActivate : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="onCleanup" Id="{cb2df2d5-3f99-4775-840b-e316eda0abaa}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD onCleanup : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="onConfigure" Id="{b445550a-17f8-4a89-8904-f3fefa6ffed2}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD onConfigure : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="onDeactivate" Id="{194687d5-779c-47d4-ac5b-3a1abc330cee}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD onDeactivate : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="onError" Id="{4e8f8125-bbe0-4c79-bdcf-535e4cc337cc}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD onError : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="onShutdown" Id="{90b49e87-3931-439e-b772-261b7c0ce671}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD onShutdown : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="path" Id="{7b15e603-1229-44d2-a319-0cd2bd72fbd3}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY path : STRING
]]></Declaration>
      <Get Name="Get" Id="{513278b6-60f5-42e2-8a48-372676e6e9a8}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="shutdown" Id="{b61bdaeb-e8b4-4d98-b6cc-7df80c6503df}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD shutdown : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="state" Id="{99880d3b-455d-448e-b5fe-94967a81b5bf}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY state : eState
]]></Declaration>
      <Get Name="Get" Id="{82475a89-7c2c-40cd-967c-a99c005cb0f5}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{4e5e4205-b31d-46d8-92e7-3390de6f0fba}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Method Name="stop" Id="{d54c754f-d655-4901-a0aa-5f2ff9092785}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD stop : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="SwitchTool" Id="{feecf5b1-bfe8-4c60-b432-d11e44f3e4ca}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD SwitchTool : UINT
VAR_INPUT
	tool	: stTool;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="TCPPosition" Id="{7d9b2ac8-8f04-4952-be38-de130752cbec}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY TCPPosition : stPose3D
]]></Declaration>
      <Get Name="Get" Id="{12d4db03-4ede-4375-ac44-18c351c505b7}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="TCPVelocity" Id="{f624a5e4-fb7d-4655-b9f1-35ecefe59c83}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY TCPVelocity : stPose3D
]]></Declaration>
      <Get Name="Get" Id="{85665c46-911d-4e9f-9fff-5d7c068e6a04}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>