<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="TEST_ROBOT" Id="{3d4a752f-ee02-4c99-bf57-025f171972f4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TEST_ROBOT EXTENDS FB_2_ROB_MANIP
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[CYCLIC_MANIP();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>