<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="TEST2" Id="{902490ce-b523-4026-8736-aa39324a4acc}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM TEST2

VAR
	Life: FB_0_BASE;
	CAM: FB_VN_GevCameraControl;
	QR: Skill_ReadQRCode;
	
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[Life();
Life.CYCLIC_BASE();
QR(pCamera:=ADR(CAM),pOwner:=ADR(Life));]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>