<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="TEST_Skill" Id="{fad47d1f-584c-43ef-9a86-749ff5c8ae2a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TEST_Skill EXTENDS FB_1_Skill
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>