<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="Skill_PickPlace" Id="{19f0d2dc-4f3e-4476-b186-4f85a96e59fa}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Skill_PickPlace  EXTENDS FB_1_Skill
// FB_2_Skill_SFC
VAR_INPUT
	pRob: POINTER TO FB_2_ROB_MANIP;
	{attribute 'OPC.UA.DA.StructuredType':=1}
	{attribute 'OPC.UA.DA' := '1'}
	Param: POINTER TO stParam_PickPlace;
	SFCInit: BOOL;
END_VAR
VAR_OUTPUT
	
END_VAR
VAR
	approachpick, approachplace,pickpos,placepos : ST_Pose;


	

	res: eResult;
	bCalcApproachDone: BOOL;
	phase: INT;

	Settings: stBA_Settings;

	bMoveInProcess: BOOL;
	bMovePickApproachDone: BOOL;
	bMovePickDone: BOOL;
	runningSkill: POINTER TO FB_1_Skill;
	bGripperCloseDone: BOOL;
	bRetractPickDone: BOOL;
	bMovePlaceApproachDone: BOOL;
	bMovePlaceDone: BOOL;
	bGripperOpenDone: BOOL;
	bRetractPlaceDone: BOOL;
	middlepoint: ST_Pose;
	bGotMiddlePoint: BOOL;
	bveMiddlePointDone: BOOL;
	bMoveMiddlePointDone: BOOL;
	T_Point: ST_TransformMatrix;
	
	T_Offset: ST_TransformMatrix;
	T_Result: ST_TransformMatrix;
END_VAR]]></Declaration>
    <Implementation>
      <SFC>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="SFCImplementationObject">
              <o n="Root" t="SFCSegment">
                <o n="ElementList" t="SFCElementList">
                  <l2 n="InnerList">
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Init"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">74L</v>
                          <v n="IdParent">85L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">75L</v>
                          <v n="IdParent">85L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">76L</v>
                          <v n="IdParent">85L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">77L</v>
                          <v n="IdParent">85L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"TRUE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">78L</v>
                          <v n="IdParent">85L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">79L</v>
                          <v n="IdParent">85L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">80L</v>
                          <v n="IdParent">85L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">81L</v>
                          <v n="IdParent">85L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Init_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">82L</v>
                          <v n="IdParent">85L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">83L</v>
                          <v n="IdParent">85L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Init_exit"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">84L</v>
                          <v n="IdParent">85L</v>
                        </o>
                      </l2>
                      <v n="Id">85L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"Init__to__Get_Data"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"State=eState.Active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">86L</v>
                          <v n="IdParent">92L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">87L</v>
                          <v n="IdParent">92L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">88L</v>
                          <v n="IdParent">92L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">89L</v>
                          <v n="IdParent">92L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">90L</v>
                          <v n="IdParent">92L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">91L</v>
                          <v n="IdParent">92L</v>
                        </o>
                      </l2>
                      <v n="Id">92L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Get_Data"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">93L</v>
                          <v n="IdParent">104L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">94L</v>
                          <v n="IdParent">104L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">95L</v>
                          <v n="IdParent">104L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">96L</v>
                          <v n="IdParent">104L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">97L</v>
                          <v n="IdParent">104L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">98L</v>
                          <v n="IdParent">104L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">99L</v>
                          <v n="IdParent">104L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">100L</v>
                          <v n="IdParent">104L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"_aCalc_Approach_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">101L</v>
                          <v n="IdParent">104L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">102L</v>
                          <v n="IdParent">104L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">103L</v>
                          <v n="IdParent">104L</v>
                        </o>
                      </l2>
                      <v n="Id">104L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"Get_Data__to__MoveJ_PickApproach"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"bCalcApproachDone"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">105L</v>
                          <v n="IdParent">111L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">106L</v>
                          <v n="IdParent">111L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">107L</v>
                          <v n="IdParent">111L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">108L</v>
                          <v n="IdParent">111L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">109L</v>
                          <v n="IdParent">111L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">110L</v>
                          <v n="IdParent">111L</v>
                        </o>
                      </l2>
                      <v n="Id">111L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"MoveJ_PickApproach"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">112L</v>
                          <v n="IdParent">123L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">113L</v>
                          <v n="IdParent">123L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">114L</v>
                          <v n="IdParent">123L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">115L</v>
                          <v n="IdParent">123L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">116L</v>
                          <v n="IdParent">123L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">117L</v>
                          <v n="IdParent">123L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">118L</v>
                          <v n="IdParent">123L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">119L</v>
                          <v n="IdParent">123L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"_aMoveJ_PickApproach_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">120L</v>
                          <v n="IdParent">123L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"MoveJ_PickApproach_entry"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">121L</v>
                          <v n="IdParent">123L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"MoveJ_PickApproach_exit"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">122L</v>
                          <v n="IdParent">123L</v>
                        </o>
                      </l2>
                      <v n="Id">123L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"MoveJ_PickApproach__to__MoveL_Pick"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"bMovePickApproachDone"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">124L</v>
                          <v n="IdParent">130L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">125L</v>
                          <v n="IdParent">130L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">126L</v>
                          <v n="IdParent">130L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">127L</v>
                          <v n="IdParent">130L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">128L</v>
                          <v n="IdParent">130L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">129L</v>
                          <v n="IdParent">130L</v>
                        </o>
                      </l2>
                      <v n="Id">130L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"MoveL_Pick"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">131L</v>
                          <v n="IdParent">142L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">132L</v>
                          <v n="IdParent">142L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">133L</v>
                          <v n="IdParent">142L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">134L</v>
                          <v n="IdParent">142L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">135L</v>
                          <v n="IdParent">142L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">136L</v>
                          <v n="IdParent">142L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">137L</v>
                          <v n="IdParent">142L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">138L</v>
                          <v n="IdParent">142L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"_aMoveL_Pick_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">139L</v>
                          <v n="IdParent">142L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"MoveL_Pick_entry"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">140L</v>
                          <v n="IdParent">142L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"MoveL_Pick_exit"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">141L</v>
                          <v n="IdParent">142L</v>
                        </o>
                      </l2>
                      <v n="Id">142L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"MoveL_Pick__to__Gripper_Close"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"bMovePickDone"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">143L</v>
                          <v n="IdParent">149L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">144L</v>
                          <v n="IdParent">149L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">145L</v>
                          <v n="IdParent">149L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">146L</v>
                          <v n="IdParent">149L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">147L</v>
                          <v n="IdParent">149L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">148L</v>
                          <v n="IdParent">149L</v>
                        </o>
                      </l2>
                      <v n="Id">149L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Gripper_Close"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">150L</v>
                          <v n="IdParent">161L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">151L</v>
                          <v n="IdParent">161L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">152L</v>
                          <v n="IdParent">161L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">153L</v>
                          <v n="IdParent">161L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">154L</v>
                          <v n="IdParent">161L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">155L</v>
                          <v n="IdParent">161L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">156L</v>
                          <v n="IdParent">161L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">157L</v>
                          <v n="IdParent">161L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Gripper_Close_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">158L</v>
                          <v n="IdParent">161L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">159L</v>
                          <v n="IdParent">161L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">160L</v>
                          <v n="IdParent">161L</v>
                        </o>
                      </l2>
                      <v n="Id">161L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"Gripper_Close__to__MoveL_RetractPick"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"bGripperCloseDone"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">162L</v>
                          <v n="IdParent">168L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">163L</v>
                          <v n="IdParent">168L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">164L</v>
                          <v n="IdParent">168L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">165L</v>
                          <v n="IdParent">168L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">166L</v>
                          <v n="IdParent">168L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">167L</v>
                          <v n="IdParent">168L</v>
                        </o>
                      </l2>
                      <v n="Id">168L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"MoveL_RetractPick"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">169L</v>
                          <v n="IdParent">180L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">170L</v>
                          <v n="IdParent">180L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">171L</v>
                          <v n="IdParent">180L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">172L</v>
                          <v n="IdParent">180L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">173L</v>
                          <v n="IdParent">180L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">174L</v>
                          <v n="IdParent">180L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">175L</v>
                          <v n="IdParent">180L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">176L</v>
                          <v n="IdParent">180L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"_aMoveL_RetractPick_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">177L</v>
                          <v n="IdParent">180L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"MoveL_RetractPick_entry"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">178L</v>
                          <v n="IdParent">180L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"MoveL_RetractPick_exit"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">179L</v>
                          <v n="IdParent">180L</v>
                        </o>
                      </l2>
                      <v n="Id">180L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"MoveL_RetractPick__to__Decide"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"bRetractPickDone"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">181L</v>
                          <v n="IdParent">187L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">182L</v>
                          <v n="IdParent">187L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">183L</v>
                          <v n="IdParent">187L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">184L</v>
                          <v n="IdParent">187L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">185L</v>
                          <v n="IdParent">187L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">186L</v>
                          <v n="IdParent">187L</v>
                        </o>
                      </l2>
                      <v n="Id">187L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Decide"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">394L</v>
                          <v n="IdParent">393L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">395L</v>
                          <v n="IdParent">393L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">396L</v>
                          <v n="IdParent">393L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">397L</v>
                          <v n="IdParent">393L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">398L</v>
                          <v n="IdParent">393L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">399L</v>
                          <v n="IdParent">393L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">400L</v>
                          <v n="IdParent">393L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">401L</v>
                          <v n="IdParent">393L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">402L</v>
                          <v n="IdParent">393L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">403L</v>
                          <v n="IdParent">393L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">404L</v>
                          <v n="IdParent">393L</v>
                        </o>
                      </l2>
                      <v n="Id">393L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCBranch">
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" cet="SFCSegment">
                          <o>
                            <o n="ElementList" t="SFCElementList">
                              <l2 n="InnerList">
                                <o t="SFCTransition">
                                  <v n="VariableName">"Branch0__Decide__to__Direct"</v>
                                  <n n="EmbeddedTransition" />
                                  <l2 n="EmbeddedTransitionProperties" />
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"NOT Param^.bPassTroughMiddlePoint"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">413L</v>
                                      <v n="IdParent">412L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">414L</v>
                                      <v n="IdParent">412L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">415L</v>
                                      <v n="IdParent">412L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">416L</v>
                                      <v n="IdParent">412L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">417L</v>
                                      <v n="IdParent">412L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">418L</v>
                                      <v n="IdParent">412L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">412L</v>
                                  <v n="IdParent">373L</v>
                                </o>
                                <o t="SFCStep">
                                  <n n="EmbeddedMainAction" />
                                  <n n="EmbeddedEntryAction" />
                                  <n n="EmbeddedExitAction" />
                                  <l2 n="EmbeddedMainActionProperties" />
                                  <l2 n="EmbeddedEntryActionProperties" />
                                  <l2 n="EmbeddedExitActionProperties" />
                                  <o n="ElementList" t="SFCElementList">
                                    <l2 n="InnerList" />
                                  </o>
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"Direct"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">357L</v>
                                      <v n="IdParent">356L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">358L</v>
                                      <v n="IdParent">356L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">359L</v>
                                      <v n="IdParent">356L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">360L</v>
                                      <v n="IdParent">356L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">361L</v>
                                      <v n="IdParent">356L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">362L</v>
                                      <v n="IdParent">356L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">363L</v>
                                      <v n="IdParent">356L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">364L</v>
                                      <v n="IdParent">356L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">365L</v>
                                      <v n="IdParent">356L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">366L</v>
                                      <v n="IdParent">356L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">367L</v>
                                      <v n="IdParent">356L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">356L</v>
                                  <v n="IdParent">373L</v>
                                </o>
                                <o t="SFCTransition">
                                  <v n="VariableName">"Direct__to__MoveJ_PlaceApproach"</v>
                                  <n n="EmbeddedTransition" />
                                  <l2 n="EmbeddedTransitionProperties" />
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"TRUE"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">406L</v>
                                      <v n="IdParent">405L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">407L</v>
                                      <v n="IdParent">405L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">408L</v>
                                      <v n="IdParent">405L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">409L</v>
                                      <v n="IdParent">405L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">410L</v>
                                      <v n="IdParent">405L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">411L</v>
                                      <v n="IdParent">405L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">405L</v>
                                  <v n="IdParent">373L</v>
                                </o>
                              </l2>
                            </o>
                            <l2 n="Attributes" cet="SFCAttribute">
                              <o>
                                <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">374L</v>
                                <v n="IdParent">373L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">375L</v>
                                <v n="IdParent">373L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                <o n="Value" t="BoolValue">
                                  <v n="Value">"FALSE"</v>
                                  <v n="DefaultValue">"FALSE"</v>
                                </o>
                                <v n="Id">376L</v>
                                <v n="IdParent">373L</v>
                              </o>
                            </l2>
                            <v n="Id">373L</v>
                            <v n="IdParent">368L</v>
                          </o>
                          <o>
                            <o n="ElementList" t="SFCElementList">
                              <l2 n="InnerList">
                                <o t="SFCTransition">
                                  <v n="VariableName">"Branch1__Decide__to__GetMiddlePoint"</v>
                                  <n n="EmbeddedTransition" />
                                  <l2 n="EmbeddedTransitionProperties" />
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"Param^.bPassTroughMiddlePoint"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">420L</v>
                                      <v n="IdParent">419L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">421L</v>
                                      <v n="IdParent">419L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">422L</v>
                                      <v n="IdParent">419L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">423L</v>
                                      <v n="IdParent">419L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">424L</v>
                                      <v n="IdParent">419L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">425L</v>
                                      <v n="IdParent">419L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">419L</v>
                                  <v n="IdParent">377L</v>
                                </o>
                                <o t="SFCStep">
                                  <n n="EmbeddedMainAction" />
                                  <n n="EmbeddedEntryAction" />
                                  <n n="EmbeddedExitAction" />
                                  <l2 n="EmbeddedMainActionProperties" />
                                  <l2 n="EmbeddedEntryActionProperties" />
                                  <l2 n="EmbeddedExitActionProperties" />
                                  <o n="ElementList" t="SFCElementList">
                                    <l2 n="InnerList" />
                                  </o>
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"GetMiddlePoint"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">427L</v>
                                      <v n="IdParent">426L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">428L</v>
                                      <v n="IdParent">426L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">429L</v>
                                      <v n="IdParent">426L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">430L</v>
                                      <v n="IdParent">426L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">431L</v>
                                      <v n="IdParent">426L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">432L</v>
                                      <v n="IdParent">426L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">433L</v>
                                      <v n="IdParent">426L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">434L</v>
                                      <v n="IdParent">426L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"GetMiddlePoint_active"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">435L</v>
                                      <v n="IdParent">426L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">436L</v>
                                      <v n="IdParent">426L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">437L</v>
                                      <v n="IdParent">426L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">426L</v>
                                  <v n="IdParent">377L</v>
                                </o>
                                <o t="SFCTransition">
                                  <v n="VariableName">"GetMiddlePoint__to__GoOverMiddleState"</v>
                                  <n n="EmbeddedTransition" />
                                  <l2 n="EmbeddedTransitionProperties" />
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"bGotMiddlePoint"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">439L</v>
                                      <v n="IdParent">438L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">440L</v>
                                      <v n="IdParent">438L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">441L</v>
                                      <v n="IdParent">438L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">442L</v>
                                      <v n="IdParent">438L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">443L</v>
                                      <v n="IdParent">438L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">444L</v>
                                      <v n="IdParent">438L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">438L</v>
                                  <v n="IdParent">377L</v>
                                </o>
                                <o t="SFCStep">
                                  <n n="EmbeddedMainAction" />
                                  <n n="EmbeddedEntryAction" />
                                  <n n="EmbeddedExitAction" />
                                  <l2 n="EmbeddedMainActionProperties" />
                                  <l2 n="EmbeddedEntryActionProperties" />
                                  <l2 n="EmbeddedExitActionProperties" />
                                  <o n="ElementList" t="SFCElementList">
                                    <l2 n="InnerList" />
                                  </o>
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"GoOverMiddleState"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">382L</v>
                                      <v n="IdParent">381L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">383L</v>
                                      <v n="IdParent">381L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">384L</v>
                                      <v n="IdParent">381L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">385L</v>
                                      <v n="IdParent">381L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">386L</v>
                                      <v n="IdParent">381L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">387L</v>
                                      <v n="IdParent">381L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">388L</v>
                                      <v n="IdParent">381L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">389L</v>
                                      <v n="IdParent">381L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"GoOverMiddleState_active"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">390L</v>
                                      <v n="IdParent">381L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"GoOverMiddleState_entry"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">391L</v>
                                      <v n="IdParent">381L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"GoOverMiddleState_exit"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">392L</v>
                                      <v n="IdParent">381L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">381L</v>
                                  <v n="IdParent">377L</v>
                                </o>
                                <o t="SFCTransition">
                                  <v n="VariableName">"GoOverMiddleState__to__MoveJ_PlaceApproach"</v>
                                  <n n="EmbeddedTransition" />
                                  <l2 n="EmbeddedTransitionProperties" />
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"bMoveMiddlePointDone"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">446L</v>
                                      <v n="IdParent">445L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">447L</v>
                                      <v n="IdParent">445L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">448L</v>
                                      <v n="IdParent">445L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">449L</v>
                                      <v n="IdParent">445L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">450L</v>
                                      <v n="IdParent">445L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">451L</v>
                                      <v n="IdParent">445L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">445L</v>
                                  <v n="IdParent">377L</v>
                                </o>
                              </l2>
                            </o>
                            <l2 n="Attributes" cet="SFCAttribute">
                              <o>
                                <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">378L</v>
                                <v n="IdParent">377L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">379L</v>
                                <v n="IdParent">377L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                <o n="Value" t="BoolValue">
                                  <v n="Value">"FALSE"</v>
                                  <v n="DefaultValue">"FALSE"</v>
                                </o>
                                <v n="Id">380L</v>
                                <v n="IdParent">377L</v>
                              </o>
                            </l2>
                            <v n="Id">377L</v>
                            <v n="IdParent">368L</v>
                          </o>
                        </l2>
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Branch0"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">369L</v>
                          <v n="IdParent">368L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">370L</v>
                          <v n="IdParent">368L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">371L</v>
                          <v n="IdParent">368L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">372L</v>
                          <v n="IdParent">368L</v>
                        </o>
                      </l2>
                      <v n="Id">368L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"MoveJ_PlaceApproach"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">188L</v>
                          <v n="IdParent">199L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">189L</v>
                          <v n="IdParent">199L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">190L</v>
                          <v n="IdParent">199L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">191L</v>
                          <v n="IdParent">199L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">192L</v>
                          <v n="IdParent">199L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">193L</v>
                          <v n="IdParent">199L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">194L</v>
                          <v n="IdParent">199L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">195L</v>
                          <v n="IdParent">199L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"_aMoveJ_PlaceApproach_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">196L</v>
                          <v n="IdParent">199L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"MoveJ_PlaceApproach_entry"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">197L</v>
                          <v n="IdParent">199L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"MoveJ_PlaceApproach_exit"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">198L</v>
                          <v n="IdParent">199L</v>
                        </o>
                      </l2>
                      <v n="Id">199L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"MoveJ_PlaceApproach__to__MoveL_Place"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"bMovePlaceApproachDone"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">200L</v>
                          <v n="IdParent">206L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">201L</v>
                          <v n="IdParent">206L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">202L</v>
                          <v n="IdParent">206L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">203L</v>
                          <v n="IdParent">206L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">204L</v>
                          <v n="IdParent">206L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">205L</v>
                          <v n="IdParent">206L</v>
                        </o>
                      </l2>
                      <v n="Id">206L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"MoveL_Place"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">207L</v>
                          <v n="IdParent">218L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">208L</v>
                          <v n="IdParent">218L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">209L</v>
                          <v n="IdParent">218L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">210L</v>
                          <v n="IdParent">218L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">211L</v>
                          <v n="IdParent">218L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">212L</v>
                          <v n="IdParent">218L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">213L</v>
                          <v n="IdParent">218L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">214L</v>
                          <v n="IdParent">218L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"_aMoveL_Place_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">215L</v>
                          <v n="IdParent">218L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"MoveL_Place_entry"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">216L</v>
                          <v n="IdParent">218L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"MoveL_Place_exit"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">217L</v>
                          <v n="IdParent">218L</v>
                        </o>
                      </l2>
                      <v n="Id">218L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"MoveL_Place__to__Gripper_Open"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"bMovePlaceDone"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">219L</v>
                          <v n="IdParent">225L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">220L</v>
                          <v n="IdParent">225L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">221L</v>
                          <v n="IdParent">225L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">222L</v>
                          <v n="IdParent">225L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">223L</v>
                          <v n="IdParent">225L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">224L</v>
                          <v n="IdParent">225L</v>
                        </o>
                      </l2>
                      <v n="Id">225L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Gripper_Open"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">226L</v>
                          <v n="IdParent">237L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">227L</v>
                          <v n="IdParent">237L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">228L</v>
                          <v n="IdParent">237L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">229L</v>
                          <v n="IdParent">237L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">230L</v>
                          <v n="IdParent">237L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">231L</v>
                          <v n="IdParent">237L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">232L</v>
                          <v n="IdParent">237L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">233L</v>
                          <v n="IdParent">237L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"_aGripper_Open_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">234L</v>
                          <v n="IdParent">237L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">235L</v>
                          <v n="IdParent">237L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">236L</v>
                          <v n="IdParent">237L</v>
                        </o>
                      </l2>
                      <v n="Id">237L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"Gripper_Open__to__MoveL_RetractPlace"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"bGripperOpenDone"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">238L</v>
                          <v n="IdParent">244L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">239L</v>
                          <v n="IdParent">244L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">240L</v>
                          <v n="IdParent">244L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">241L</v>
                          <v n="IdParent">244L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">242L</v>
                          <v n="IdParent">244L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">243L</v>
                          <v n="IdParent">244L</v>
                        </o>
                      </l2>
                      <v n="Id">244L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"MoveL_RetractPlace"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">245L</v>
                          <v n="IdParent">256L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">246L</v>
                          <v n="IdParent">256L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">247L</v>
                          <v n="IdParent">256L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">248L</v>
                          <v n="IdParent">256L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">249L</v>
                          <v n="IdParent">256L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">250L</v>
                          <v n="IdParent">256L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">251L</v>
                          <v n="IdParent">256L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">252L</v>
                          <v n="IdParent">256L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"_aMoveL_RetractPlace_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">253L</v>
                          <v n="IdParent">256L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"MoveL_RetractPlace_entry"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">254L</v>
                          <v n="IdParent">256L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"MoveL_RetractPlace_exit"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">255L</v>
                          <v n="IdParent">256L</v>
                        </o>
                      </l2>
                      <v n="Id">256L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"MoveL_RetractPlace__to__Done"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"bRetractPlaceDone"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">257L</v>
                          <v n="IdParent">263L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">258L</v>
                          <v n="IdParent">263L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">259L</v>
                          <v n="IdParent">263L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">260L</v>
                          <v n="IdParent">263L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">261L</v>
                          <v n="IdParent">263L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">262L</v>
                          <v n="IdParent">263L</v>
                        </o>
                      </l2>
                      <v n="Id">263L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Done"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">264L</v>
                          <v n="IdParent">275L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">265L</v>
                          <v n="IdParent">275L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">266L</v>
                          <v n="IdParent">275L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">267L</v>
                          <v n="IdParent">275L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">268L</v>
                          <v n="IdParent">275L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">269L</v>
                          <v n="IdParent">275L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">270L</v>
                          <v n="IdParent">275L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">271L</v>
                          <v n="IdParent">275L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"_aDone_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">272L</v>
                          <v n="IdParent">275L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">273L</v>
                          <v n="IdParent">275L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">274L</v>
                          <v n="IdParent">275L</v>
                        </o>
                      </l2>
                      <v n="Id">275L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"Done__to__Init"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"State&lt;&gt;eState.Active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">276L</v>
                          <v n="IdParent">282L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">277L</v>
                          <v n="IdParent">282L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">278L</v>
                          <v n="IdParent">282L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">279L</v>
                          <v n="IdParent">282L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">280L</v>
                          <v n="IdParent">282L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">281L</v>
                          <v n="IdParent">282L</v>
                        </o>
                      </l2>
                      <v n="Id">282L</v>
                      <v n="IdParent">10L</v>
                    </o>
                    <o t="SFCJump">
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Init"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">283L</v>
                          <v n="IdParent">286L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">284L</v>
                          <v n="IdParent">286L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">285L</v>
                          <v n="IdParent">286L</v>
                        </o>
                      </l2>
                      <v n="Id">286L</v>
                      <v n="IdParent">10L</v>
                    </o>
                  </l2>
                </o>
                <l2 n="Attributes" cet="SFCAttribute">
                  <o>
                    <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                    <o n="Value" t="StringValue">
                      <v n="Value">""</v>
                      <v n="DefaultValue">""</v>
                    </o>
                    <v n="Id">59L</v>
                    <v n="IdParent">10L</v>
                  </o>
                  <o>
                    <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                    <o n="Value" t="StringValue">
                      <v n="Value">""</v>
                      <v n="DefaultValue">""</v>
                    </o>
                    <v n="Id">60L</v>
                    <v n="IdParent">10L</v>
                  </o>
                  <o>
                    <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                    <o n="Value" t="BoolValue">
                      <v n="Value">"FALSE"</v>
                      <v n="DefaultValue">"FALSE"</v>
                    </o>
                    <v n="Id">61L</v>
                    <v n="IdParent">10L</v>
                  </o>
                </l2>
                <v n="Id">10L</v>
                <v n="IdParent">-1L</v>
              </o>
              <d2 n="Categories" ckt="Guid" cvt="SFCAttributeCategory">
                <v>1c5c6e05-2bb7-4258-bcee-fd16a540c63c</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Identifier">"Specific"</v>
                  <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="Description">"Element type specific properties"</v>
                </o>
                <v>20f0fc67-978d-438b-979f-eef294f34ee4</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Identifier">"Actions"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Action definitions"</v>
                </o>
                <v>6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Identifier">"Common"</v>
                  <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="Description">"Common properties"</v>
                </o>
                <v>d336ba06-8a67-4e6b-9697-50f83ba6bdde</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Identifier">"Times"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Time definitions"</v>
                </o>
              </d2>
              <d2 n="Attributes" ckt="Guid" cvt="SFCAttributeDescription">
                <v>01580b27-6378-448b-8ecb-0e4b795b58d6</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">true</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                  <v n="Identifier">"Exclude"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Exclude this element from build"</v>
                </o>
                <v>23bdaa98-72ec-41f7-817b-9dede5697086</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                  <v n="Identifier">"Parallel"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Sets the branch to parallel mode"</v>
                </o>
                <v>38391c6d-6d4a-42f8-8ee7-9f45e5adafa8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                  <v n="Identifier">"Name"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Name of the element"</v>
                </o>
                <v>62e1754b-7629-4e63-9cec-10ae0c536f1f</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                  <v n="Identifier">"Duplication"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Copies the implementation of step actions or transitions with the element. Otherwise, copies the reference to an existing implementation."</v>
                </o>
                <v>6844a48e-46c2-4cc8-a185-a478f3b99cc0</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                  <v n="Identifier">"InitStep"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Sets the step as the initial step"</v>
                </o>
                <v>700a583f-b4d4-43e4-8c14-629c7cd3bec8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                  <v n="Identifier">"MainAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"Name of the action to be called if the step is active"</v>
                </o>
                <v>7d894980-aeea-405c-a0f6-e2b26429c58f</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">true</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                  <v n="Identifier">"Comment"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Comment of the element"</v>
                </o>
                <v>8294df19-5962-4dee-a874-1051dabb0e3e</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                  <v n="Identifier">"Monitoring"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Indicates transition monitoring setting."</v>
                </o>
                <v>a2621e18-7de3-4ea6-ae6d-89e9e0b7befd</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                  <v n="Identifier">"ExitAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"Name of the action to be called if the step is deactivated"</v>
                </o>
                <v>a6b08bd8-b696-47e3-9cbf-7408b61c9ff8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                  <v n="Identifier">"EntryAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"Name of the action to be called if the step is activated"</v>
                </o>
                <v>b693554c-1b01-4a8d-afde-9e3a46f7465d</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                  <v n="Identifier">"MaxTime"</v>
                  <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Description">"Defines the maximal active time for the step"</v>
                </o>
                <v>bc882c11-1e91-4dd8-a6b8-2075724ed18b</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                  <v n="Identifier">"Symbol"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Symbol configuration setting of the element"</v>
                </o>
                <v>cacf1a68-236e-47c2-b7b1-1cf9199718cb</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                  <v n="Identifier">"MinTime"</v>
                  <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Description">"Defines the minimal active time for the step"</v>
                </o>
                <v>e174fc0d-80b0-4a9e-a530-ca239c249a50</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                  <v n="Identifier">"Qualifier"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Qualifier of the action association"</v>
                </o>
              </d2>
              <d2 n="EnumTemplates" ckt="Guid" cvt="EnumValueTemplate">
                <v>6ecff51c-9b8f-4338-aab0-67c2b31b07e9</v>
                <o>
                  <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                  <l n="Values" t="ArrayList" cet="EnumEntry">
                    <o>
                      <v n="Identifier">"None"</v>
                      <v n="Value">0L</v>
                      <v n="Key">"None"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Variable"</v>
                      <v n="Value">1L</v>
                      <v n="Key">"Variable"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Call"</v>
                      <v n="Value">2L</v>
                      <v n="Key">"Call"</v>
                    </o>
                  </l>
                  <v n="BaseType">"INT"</v>
                </o>
                <v>79a4fdd5-c859-4de4-aa8d-c03372c880c2</v>
                <o>
                  <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                  <l n="Values" t="ArrayList" cet="EnumEntry">
                    <o>
                      <v n="Identifier">"Unspecified"</v>
                      <v n="Value">0L</v>
                      <v n="Key">"Unspecified"</v>
                    </o>
                    <o>
                      <v n="Identifier">"None"</v>
                      <v n="Value">1L</v>
                      <v n="Key">"None"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Read"</v>
                      <v n="Value">2L</v>
                      <v n="Key">"Read"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Write"</v>
                      <v n="Value">3L</v>
                      <v n="Key">"Write"</v>
                    </o>
                    <o>
                      <v n="Identifier">"ReadWrite"</v>
                      <v n="Value">4L</v>
                      <v n="Key">"ReadWrite"</v>
                    </o>
                  </l>
                  <v n="BaseType">"INT"</v>
                </o>
              </d2>
              <v n="ImplId">9L</v>
            </o>
          </Data>
          <TypeList>
            <Type n="ArrayList">System.Collections.ArrayList</Type>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoolValue">{89e1c7bb-c9f8-4be3-b8a7-019cdbb9f7e8}</Type>
            <Type n="EnumEntry">{4185e6da-1717-44c9-b705-102861764479}</Type>
            <Type n="EnumValue">{4dd7572b-4b9d-4d35-963e-6a34a4aaa5c1}</Type>
            <Type n="EnumValueTemplate">{d6bfe4f0-d62f-4b5f-9f95-2bbeb1950e28}</Type>
            <Type n="Guid">System.Guid</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="SFCAttribute">{21f3f16e-04fa-4637-b6b7-d84e4192e99f}</Type>
            <Type n="SFCAttributeCategory">{679adacf-f2a4-4167-a3f7-d21cfc5d451f}</Type>
            <Type n="SFCAttributeDescription">{d851789d-af2c-4990-9d48-a7bdc9181773}</Type>
            <Type n="SFCBranch">{e221b778-bb8f-44ba-8a6a-f796287d4e62}</Type>
            <Type n="SFCElementList">{587d6556-cfe6-4e76-9cc9-fc0daf0c8c29}</Type>
            <Type n="SFCImplementationObject">{74f81948-1328-492c-b6c1-a9ea72048b28}</Type>
            <Type n="SFCJump">{7e39ac27-154f-419a-a255-6a6cf37d5ed0}</Type>
            <Type n="SFCSegment">{f1db7f6f-4774-46a6-ad9b-a94414f875fc}</Type>
            <Type n="SFCStep">{86ee92a2-d863-4136-be27-82b36d84211c}</Type>
            <Type n="SFCTransition">{4ecb29e8-a90a-4646-84ac-2ff54215ab29}</Type>
            <Type n="String">System.String</Type>
            <Type n="StringValue">{778c8bac-3fa0-41e1-99d3-2b628d12d3e5}</Type>
          </TypeList>
        </XmlArchive>
      </SFC>
    </Implementation>
    <Folder Name="StateControl" Id="{b8625484-5b9d-403b-b98f-c4de5899beed}" />
    <Action Name="_aCalc_Approach_active" Id="{37dfacd0-5ddb-427e-a6d5-ffb024477c13}">
      <Implementation>
        <ST><![CDATA[// TODO: Resolve Param.PickPositionName / Param.PlacePositionName to base poses.
// Apply PickPositionOffset / PlacePositionOffset and calculate approachpick / approachplace
// from PickApproachDirection / PlaceApproachDirection and the configured offsets.
// Set bCalcApproachDone := TRUE when both poses are valid.

IF phase = 0 THEN
	IF Param^.PickPositionName<>'' THEN
		res := pRob^.PM.Load(Param^.PickPositionName);
		
		IF res=SUCCESS THEN
			T_Point  := FromPose(pRob^.PM.LoadedPoint);
			T_Offset := FromPose(Param^.PickPositionOffset);
			
			T_Result := Multiply(
				A := T_Point,
				B := T_Offset
			);
			
			pickpos := ToPose(T_Result);
			phase := 10;
		ELSE
			ExecutionDone:=TRUE;
			ExecutionResult:=FAILURE;
			Deactivate();
			Messenger.AddError(eMessageCategories.MissingData,Path,'Pick Position is not defined in PM');
			SFCInit:=TRUE;
			
		END_IF
	END_IF
END_IF


IF phase = 10 THEN
	IF Param^.PlacePositionName<>'' THEN
		res := pRob^.PM.Load(Param^.PlacePositionName);
		
		IF res=SUCCESS THEN
      placepos := pROB^.PM.LoadedPoint;
      placepos.x := placepos.x + Param^.PlacePositionOffset.x;
      placepos.y := placepos.y + Param^.PlacePositionOffset.y;
      placepos.z := placepos.z + Param^.PlacePositionOffset.z;
      placepos.roll := placepos.roll + Param^.PlacePositionOffset.roll;
      placepos.pitch := placepos.pitch + Param^.PlacePositionOffset.pitch;
      placepos.yaw := placepos.yaw + Param^.PlacePositionOffset.yaw;
			phase := 20;
		ELSE
			ExecutionDone:=TRUE;
			ExecutionResult:=FAILURE;
			Deactivate();
			Messenger.AddError(eMessageCategories.MissingData,Path,'Place Position is not defined in PM');
			SFCInit:=TRUE;
			
		END_IF
	END_IF
END_IF



IF phase = 20 THEN
	approachpick := F_CalcOffsetPose(pickpos,Param^.PickApproachDirection,Param^.PickApproachOffset);
	approachplace := F_CalcOffsetPose(placepos,Param^.PlaceApproachDirection,Param^.PlaceApproachOffset);
	bCalcApproachDone := TRUE;
END_IF



]]></ST>
      </Implementation>
    </Action>
    <Action Name="_aDone_active" Id="{e89f9719-0119-4542-a78a-a5b9a7f93659}">
      <Implementation>
        <ST><![CDATA[ExecutionDone:=TRUE;
ExecutionResult:=SUCCESS;]]></ST>
      </Implementation>
    </Action>
    <Action Name="_aGripper_Close_active" Id="{9ee85894-a04e-49cb-9fef-a6b3351f6680}">
      <Implementation>
        <ST><![CDATA[

]]></ST>
      </Implementation>
    </Action>
    <Action Name="_aGripper_Open_active" Id="{cf90c9f8-9efe-4b16-b87d-425e4fed125f}">
      <Implementation>
        <ST><![CDATA[IF pRob^.TOOL^.Release() = SUCCESS THEN
	bGripperOpenDone:=TRUE;
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="_aMoveJ_PickApproach_active" Id="{92d00584-9814-4e39-8fa3-8493e89622e3}">
      <Implementation>
        <ST><![CDATA[PollRobotMove(DoneFlag := bMovePickApproachDone);
]]></ST>
      </Implementation>
    </Action>
    <Action Name="_aMoveJ_PlaceApproach_active" Id="{a42b9b23-6938-4b16-8ea5-134746ad2288}">
      <Implementation>
        <ST><![CDATA[PollRobotMove(DoneFlag := bMovePlaceApproachDone);
]]></ST>
      </Implementation>
    </Action>
    <Action Name="_aMoveL_Pick_active" Id="{73b9f592-c1d9-4003-92ee-e278bc29956d}">
      <Implementation>
        <ST><![CDATA[PollRobotMove(DoneFlag := bMovePickDone);
]]></ST>
      </Implementation>
    </Action>
    <Action Name="_aMoveL_Place_active" Id="{2c5e09cd-59b9-42e3-be17-fb01c6d6beaf}">
      <Implementation>
        <ST><![CDATA[PollRobotMove(DoneFlag := bMovePlaceDone);
]]></ST>
      </Implementation>
    </Action>
    <Action Name="_aMoveL_RetractPick_active" Id="{cffa91e5-3624-4087-864a-9d66af7cbc22}">
      <Implementation>
        <ST><![CDATA[PollRobotMove(DoneFlag := bRetractPickDone);
]]></ST>
      </Implementation>
    </Action>
    <Action Name="_aMoveL_RetractPlace_active" Id="{7ddb2123-18b0-4656-a4f2-c9374296db50}">
      <Implementation>
        <ST><![CDATA[PollRobotMove(DoneFlag := bRetractPlaceDone);
]]></ST>
      </Implementation>
    </Action>
    <Action Name="GetMiddlePoint_active" Id="{f4d50aa2-832a-4fa3-a8a2-72d5c28f6d4c}">
      <Implementation>
        <ST><![CDATA[// TODO: Resolve Param.PickPositionName / Param.PlacePositionName to base poses.
// Apply PickPositionOffset / PlacePositionOffset and calculate approachpick / approachplace
// from PickApproachDirection / PlaceApproachDirection and the configured offsets.
// Set bCalcApproachDone := TRUE when both poses are valid.

IF Param^.MiddlePointName<>'' THEN
	res := pRob^.PM.Load(Param^.MiddlePointName);
	
	IF res=SUCCESS THEN
		middlepoint := pROB^.PM.LoadedPoint;
		bGotMiddlePoint := TRUE;
	END_IF
END_IF


]]></ST>
      </Implementation>
    </Action>
    <Action Name="GoOverMiddleState_active" Id="{7db3ba8f-331b-4fb1-bdef-854308e83b1d}">
      <Implementation>
        <ST><![CDATA[PollRobotMove(DoneFlag := bMoveMiddlePointDone);
]]></ST>
      </Implementation>
    </Action>
    <Action Name="GoOverMiddleState_entry" Id="{26f5b4c1-e04f-4111-8bad-0c088371fe18}">
      <Implementation>
        <ST><![CDATA[Settings.Target.pose:=middlepoint;
Settings.Target.frame_id:= eRefFrame.BRF;
Settings.Velocity:=Param^.FastVelocity;


nCalledMoveID := pRob^.MoveJoint(
  Target := Settings.Target,
  Velocity := Param^.FastVelocity);
HandleMoveStart();
]]></ST>
      </Implementation>
    </Action>
    <Action Name="GoOverMiddleState_exit" Id="{c627f6fa-cc85-4a31-8f6e-63da895398bc}">
      <Implementation>
        <ST><![CDATA[nCalledMoveID:=0;
bMoveInProcess:=FALSE;
bMoveMiddlePointDone:=FALSE;]]></ST>
      </Implementation>
    </Action>
    <Action Name="Gripper_Close_active" Id="{b462e5a3-d3e4-40a1-b1d0-970ba279ea7b}">
      <Implementation>
        <ST><![CDATA[IF pRob^.TOOL^.Grip() = SUCCESS THEN
	bGripperCloseDone:=TRUE;
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="Gripper_Close_entry" Id="{dfa66bf6-7f5b-4a42-b3f9-0a95de0f88f9}">
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Action>
    <Action Name="Gripper_Close_exit" Id="{1a37bfea-119a-434a-994d-1e022c907901}">
      <Implementation>
        <ST><![CDATA[bSubSkillRunning:=FALSE;]]></ST>
      </Implementation>
    </Action>
    <Action Name="Init_active" Id="{bb9d285b-87dd-4209-82d5-a350113088c8}">
      <Implementation>
        <ST><![CDATA[phase:=0;
nCalledMoveID := 0;
bMoveInProcess := FALSE;

bMovePickApproachDone	:=FALSE;
bMovePickDone			:=FALSE;
bGripperCloseDone		:=FALSE;
bRetractPickDone		:=FALSE;
bMovePlaceApproachDone	:=FALSE;
bMovePlaceDone			:=FALSE;
bGripperOpenDone		:=FALSE;
bRetractPlaceDone		:=FALSE;
bGotMiddlePoint			:=FALSE;
bveMiddlePointDone		:=FALSE;
bMoveMiddlePointDone	:=FALSE;]]></ST>
      </Implementation>
    </Action>
    <Action Name="Init_exit" Id="{d8ae8678-7787-4082-8e7b-633a4307d317}">
      <Implementation>
        <ST><![CDATA[ExecutionDone:=FALSE;
ExecutionResult:=NONE;

phase:=0;
nCalledMoveID := 0;
bMoveInProcess := FALSE;

bMovePickApproachDone	:=FALSE;
bMovePickDone			:=FALSE;
bGripperCloseDone		:=FALSE;
bRetractPickDone		:=FALSE;
bMovePlaceApproachDone	:=FALSE;
bMovePlaceDone			:=FALSE;
bGripperOpenDone		:=FALSE;
bRetractPlaceDone		:=FALSE;
bGotMiddlePoint			:=FALSE;
bveMiddlePointDone		:=FALSE;
bMoveMiddlePointDone	:=FALSE;]]></ST>
      </Implementation>
    </Action>
    <Action Name="MoveJ_PickApproach_entry" Id="{81ae2925-3ee5-40ec-bd66-01c408ed70f4}">
      <Implementation>
        <ST><![CDATA[bCalcApproachDone:=FALSE;


Settings.Target.pose:=approachpick;
Settings.Target.frame_id:= eRefFrame.BRF;
Settings.Velocity:=Param^.FastVelocity;


nCalledMoveID := pRob^.MoveJoint(
  Target := Settings.Target,
  Velocity := Param^.FastVelocity);
HandleMoveStart();
]]></ST>
      </Implementation>
    </Action>
    <Action Name="MoveJ_PickApproach_exit" Id="{e2f5d488-d4c7-4a0e-a42e-a26a64f7b9c5}">
      <Implementation>
        <ST><![CDATA[nCalledMoveID:=0;
bMoveInProcess:=FALSE;
bMovePickApproachDone := FALSE;]]></ST>
      </Implementation>
    </Action>
    <Action Name="MoveJ_PlaceApproach_entry" Id="{832e16b5-ffc9-47bb-8153-73fd53b7df55}">
      <Implementation>
        <ST><![CDATA[Settings.Target.pose:=approachplace;
Settings.Target.frame_id:= eRefFrame.BRF;

Settings.Velocity:=Param^.FastVelocity;


nCalledMoveID := pRob^.MoveJoint(
  Target := Settings.Target,
  Velocity := Param^.FastVelocity);
HandleMoveStart();
]]></ST>
      </Implementation>
    </Action>
    <Action Name="MoveJ_PlaceApproach_exit" Id="{5229f4b1-1f3d-4f1d-bbe3-c51f7e0fb745}">
      <Implementation>
        <ST><![CDATA[nCalledMoveID:=0;
bMoveInProcess:=FALSE;
bMovePlaceApproachDone := FALSE;]]></ST>
      </Implementation>
    </Action>
    <Action Name="MoveL_Pick_entry" Id="{0cdfa23a-60a7-423e-9402-9b391ce28731}">
      <Implementation>
        <ST><![CDATA[

Settings.Target.pose:=pickpos;
Settings.Target.frame_id:= eRefFrame.BRF;
Settings.Velocity:=Param^.SlowVelocity;


nCalledMoveID := pRob^.MoveLinear(
  Target := Settings.Target,
  Velocity := Param^.SlowVelocity);
HandleMoveStart();
]]></ST>
      </Implementation>
    </Action>
    <Action Name="MoveL_Pick_exit" Id="{73135b79-08b7-4530-8720-be518dca25f8}">
      <Implementation>
        <ST><![CDATA[nCalledMoveID:=0;
bMoveInProcess:=FALSE;
bMovePickDone := FALSE;]]></ST>
      </Implementation>
    </Action>
    <Action Name="MoveL_Place_entry" Id="{a4302577-19dd-47de-9f54-8cd72711ffe8}">
      <Implementation>
        <ST><![CDATA[Settings.Target.pose:=placepos;
Settings.Target.frame_id:= eRefFrame.BRF;

Settings.Velocity:=Param^.SlowVelocity;


nCalledMoveID := pRob^.MoveLinear(
  Target := Settings.Target,
  Velocity := Param^.SlowVelocity);
HandleMoveStart();
]]></ST>
      </Implementation>
    </Action>
    <Action Name="MoveL_Place_exit" Id="{84a61dec-1718-453c-a818-66168ad7e659}">
      <Implementation>
        <ST><![CDATA[nCalledMoveID:=0;
bMoveInProcess:=FALSE;
bMovePlaceDone := FALSE;
]]></ST>
      </Implementation>
    </Action>
    <Action Name="MoveL_RetractPick_entry" Id="{17e20099-1738-4082-955e-656ad5d96d34}">
      <Implementation>
        <ST><![CDATA[Settings.Target.pose:=approachpick;
Settings.Target.frame_id:= eRefFrame.BRF;
Settings.Velocity:=Param^.SlowVelocity;


nCalledMoveID := pRob^.MoveLinear(
  Target := Settings.Target,
  Velocity := Param^.SlowVelocity);
HandleMoveStart();
]]></ST>
      </Implementation>
    </Action>
    <Action Name="MoveL_RetractPick_exit" Id="{a05a6f6a-3c5c-4092-86c8-c0c55643a997}">
      <Implementation>
        <ST><![CDATA[nCalledMoveID:=0;
bMoveInProcess:=FALSE;
bRetractPickDone := FALSE;]]></ST>
      </Implementation>
    </Action>
    <Action Name="MoveL_RetractPlace_entry" Id="{48b6db56-5e1b-4e06-960d-59187aa3853a}">
      <Implementation>
        <ST><![CDATA[Settings.Target.pose:=approachplace;
Settings.Target.frame_id:= eRefFrame.BRF;

Settings.Velocity:=Param^.SlowVelocity;


nCalledMoveID := pRob^.MoveLinear(
  Target := Settings.Target,
  Velocity := Param^.SlowVelocity);
HandleMoveStart();
]]></ST>
      </Implementation>
    </Action>
    <Action Name="MoveL_RetractPlace_exit" Id="{5c7fa900-9614-4520-a58b-fa98fb8c9bc2}">
      <Implementation>
        <ST><![CDATA[nCalledMoveID:=0;
bMoveInProcess:=FALSE;
bRetractPlaceDone := FALSE;
]]></ST>
      </Implementation>
    </Action>
      <Method Name="HandleMoveStart" Id="{57dbf99b-ec72-47c9-a087-a8267dfa732e}">
        <Declaration><![CDATA[METHOD HandleMoveStart : BOOL
  ]]></Declaration>
        <Implementation>
          <ST><![CDATA[HandleMoveStart := nCalledMoveID <> 0;

  IF NOT HandleMoveStart THEN
      ExecutionDone := TRUE;
      ExecutionResult := FAILURE;
      Messenger.AddWarn(eMessageCategories.ParentFailed, Path, 'Robot rejected move');
      SFCInit := TRUE;
  END_IF
  ]]></ST>
        </Implementation>
      </Method>
      <Method Name="PollRobotMove" Id="{78fd90e9-ae41-49ae-a2ac-70ab9188a9db}">
        <Declaration><![CDATA[METHOD PollRobotMove : BOOL
    VAR_IN_OUT
      DoneFlag : BOOL;
    END_VAR
    ]]></Declaration>
        <Implementation>
        <ST><![CDATA[PollRobotMove := FALSE;

    IF pRob = 0 THEN
      ExecutionDone := TRUE;
      ExecutionResult := ERROR;
      Messenger.AddError(eMessageCategories.MissingData, Path, 'Robot is not assigned');
      SFCInit := TRUE;
      RETURN;
    END_IF

    IF (nCalledMoveID = 0) OR (pRob^.CommandID <> nCalledMoveID) THEN
      RETURN;
    END_IF

    bMoveInProcess := TRUE;

    CASE pRob^.CommandState OF
      INIT, ACKNOWLEDGE, RUNNING:
        PollRobotMove := FALSE;

      FINALIZED:
        IF pRob^.CommandResult = SUCCESS THEN
          DoneFlag := TRUE;
          PollRobotMove := TRUE;
        ELSE
          ExecutionDone := TRUE;
          IF pRob^.CommandResult = NONE THEN
            ExecutionResult := ERROR;
          ELSE
            ExecutionResult := pRob^.CommandResult;
          END_IF
          Messenger.AddWarn(eMessageCategories.ParentFailed, Path, 'Robot move failed');
          SFCInit := TRUE;
        END_IF

      ABORTED:
        ExecutionDone := TRUE;
        ExecutionResult := FAILURE;
        Messenger.AddWarn(eMessageCategories.ParentFailed, Path, 'Robot move aborted');
        SFCInit := TRUE;
    END_CASE
    ]]></ST>
        </Implementation>
      </Method>
    <Method Name="OnActivate" Id="{fe361160-cff6-4374-b8d5-b6aa8065f810}" FolderPath="StateControl\">
      <Declaration><![CDATA[METHOD PROTECTED OnActivate : eResult
VAR_INPUT
END_VAR

VAR
	eParentResult: eResult;
	myResult: ERESULT;
END_VAR

VAR //YOUR CODE
	succ : BOOL;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[eParentResult := SUPER^.OnActivate();
//--------------------------------------------------
myResult:=NONE;
// ----- YOUR CODE HERE (incl. Alarms) -------------

SFCInit:=FALSE;
myResult:=SUCCESS;



// ----- END YOUR CODE -----------------------------
//--------------------------------------------------
OnActivate := CombineResults(eParentResult,myResult);
]]></ST>
      </Implementation>
    </Method>
    <Method Name="OnDeactivate" Id="{b3c5dbd6-4410-45d6-8fa7-b9583ee78948}" FolderPath="StateControl\">
      <Declaration><![CDATA[METHOD PROTECTED OnDeactivate : eResult
VAR_INPUT
END_VAR

VAR
	eParentResult: eResult;
	myResult: ERESULT;
END_VAR

VAR //YOUR CODE
	succ : BOOL;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[eParentResult := SUPER^.OnDeactivate();
//--------------------------------------------------
myResult:=NONE;
// ----- YOUR CODE HERE (incl. Alarms) -------------

SFCInit:=TRUE;
myResult:=SUCCESS;
bMoveInProcess:=FALSE;

// ----- END YOUR CODE -----------------------------
//--------------------------------------------------
OnDeactivate := CombineResults(eParentResult,myResult);
]]></ST>
      </Implementation>
    </Method>
    <Method Name="OnError" Id="{399d5806-abb9-4580-87f6-befc1c718003}" FolderPath="StateControl\">
      <Declaration><![CDATA[METHOD PROTECTED OnError : eResult
VAR_INPUT
END_VAR

VAR
	eParentResult: eResult;
	myResult: ERESULT;
END_VAR

VAR //YOUR CODE
	succ : BOOL;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[eParentResult := SUPER^.OnError();

myResult := NONE;

// ----- YOUR CODE HERE -----------------------------
SFCInit:=TRUE;
myResult := SUCCESS;

// ----- END YOUR CODE ------------------------------

OnError := CombineResults(eParentResult, myResult);]]></ST>
      </Implementation>
    </Method>
    <Method Name="OnShutdown" Id="{8cf91fc1-76e2-44cf-a181-f40f308b193c}" FolderPath="StateControl\">
      <Declaration><![CDATA[METHOD PROTECTED OnShutdown : eResult
VAR_INPUT
END_VAR

    VAR
    	eParentResult: eResult;
    	myResult: ERESULT;
    END_VAR

    VAR //YOUR CODE
    	succ : BOOL;
    END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[eParentResult := SUPER^.OnShutdown();
//--------------------------------------------------
myResult:=NONE;
// ----- YOUR CODE HERE (incl. Alarms) -------------


SFCInit:=TRUE;
myResult:=SUCCESS;

// ----- END YOUR CODE -----------------------------
//--------------------------------------------------
OnShutdown := CombineResults(eParentResult,myResult);
]]></ST>
      </Implementation>
    </Method>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="SFCProperty">
            <n n="SFCErrorAnalyzation" />
            <n n="SFCErrorAnalyzationTable" />
            <n n="SFCCurrentSteps" />
            <n n="SFCMetaSteps" />
            <v n="Title">"IecSfc"</v>
            <v n="Company">"System"</v>
            <v n="Version">"4.4.0.0"</v>
            <v n="Namespace">""</v>
            <d2 n="Flags" ckt="Flags" cvt="SFCPropertyFlagData">
              <v>EnableLimit</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Init</v>
              <o>
                <v n="Use">true</v>
                <v n="Declare">true</v>
              </o>
              <v>Reset</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>QuitError</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Pause</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Error</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Trans</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>ErrorStep</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>ErrorPOU</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>CurrentStep</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Tip</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>TipMode</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>SFCErrorAnalyzation</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>SFCErrorAnalyzationTable</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>CurrentSteps</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>MetaSteps</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">false</v>
              </o>
            </d2>
            <v n="CalcActiveTransOnly">true</v>
            <v n="UseDefaults">false</v>
          </o>
        </Data>
        <TypeList>
          <Type n="Boolean">System.Boolean</Type>
          <Type n="Flags">{27d8150b-ef58-4fff-8da1-1f7dd5f9ea51}</Type>
          <Type n="SFCProperty">{58548d2c-f1b1-453d-9195-66c94e2a3ae0}</Type>
          <Type n="SFCPropertyFlagData">{24565a38-6368-4874-ab9a-0ef7ec269521}</Type>
          <Type n="String">System.String</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
  </POU>
</TcPlcObject>