<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_CNC" Id="{beaddaaa-6ba4-41b1-8859-ef0168bd27cb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_CNC
VAR_INPUT

END_VAR
VAR_OUTPUT
	bDone: Bool;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="StartCycle" Id="{f7bdb1bf-f4f9-4b82-8fd3-97ff0cd58c2b}">
      <Declaration><![CDATA[METHOD StartCycle : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>