services:
  eta:
    image: orka375/ros2_kilted_eta:latest
    container_name: eta_container
    network_mode: host
    ipc: host
    privileged: true
    stdin_open: true
    tty: true

  fleet:
    image: orka375/ros2_kilted_eta_fleet:latest
    container_name: eta_fleet_container
    network_mode: host
    ipc: host
    privileged: true
    stdin_open: true
    tty: true

  gazebo:
    image: orka375/ros2_kilted_eta_gz:latest
    container_name: eta_gz_container
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    stdin_open: true
    tty: true