<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="MAIN" Id="{b53b2225-9371-4250-8b82-1e79beeb5814}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	TestBot: FB_ROB;
	H: FB_HELPER;
	UR5: FB_UR5;
	PnP : FB_PickPlaceSkill;
END_VAR


VAR

    fbDB : FB_PostgreSQLClient;


    sRobotName : STRING;


END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbDB();

// PnP(Rob:=ADR(UR5));
UR5();

UR5.CallSkill(pSkill:=ADR(UR5.PiNPl));
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>