<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_Skill" Id="{de568c3b-e8e2-4fe8-b2d6-5e89933abc51}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Skill EXTENDS FB_Base IMPLEMENTS ITF_1_Skill
VAR_INPUT
	_owner: POINTER TO FB_Base;
	SFCInit, SFCPause, SFCReset: BOOL;
END_VAR
VAR_OUTPUT
	bBusy, bDone: BOOL;
	SFCError: BOOL;
	SFCCurrentStep: STRING;
END_VAR
VAR
// 	SubSkillHandler : FB_SkillHandler;
END_VAR


]]></Declaration>
    <Implementation>
      <SFC>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="SFCImplementationObject">
              <o n="Root" t="SFCSegment">
                <o n="ElementList" t="SFCElementList">
                  <l2 n="InnerList" />
                </o>
                <l2 n="Attributes" cet="SFCAttribute">
                  <o>
                    <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                    <o n="Value" t="StringValue">
                      <v n="Value">""</v>
                      <v n="DefaultValue">""</v>
                    </o>
                    <v n="Id">11L</v>
                    <v n="IdParent">10L</v>
                  </o>
                  <o>
                    <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                    <o n="Value" t="StringValue">
                      <v n="Value">""</v>
                      <v n="DefaultValue">""</v>
                    </o>
                    <v n="Id">12L</v>
                    <v n="IdParent">10L</v>
                  </o>
                  <o>
                    <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                    <o n="Value" t="BoolValue">
                      <v n="Value">"FALSE"</v>
                      <v n="DefaultValue">"FALSE"</v>
                    </o>
                    <v n="Id">13L</v>
                    <v n="IdParent">10L</v>
                  </o>
                </l2>
                <v n="Id">10L</v>
                <v n="IdParent">-1L</v>
              </o>
              <d2 n="Categories" ckt="Guid" cvt="SFCAttributeCategory">
                <v>1c5c6e05-2bb7-4258-bcee-fd16a540c63c</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Identifier">"Specific"</v>
                  <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="Description">"Element type specific properties"</v>
                </o>
                <v>20f0fc67-978d-438b-979f-eef294f34ee4</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Identifier">"Actions"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Action definitions"</v>
                </o>
                <v>6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Identifier">"Common"</v>
                  <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="Description">"Common properties"</v>
                </o>
                <v>d336ba06-8a67-4e6b-9697-50f83ba6bdde</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Identifier">"Times"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Time definitions"</v>
                </o>
              </d2>
              <d2 n="Attributes" ckt="Guid" cvt="SFCAttributeDescription">
                <v>01580b27-6378-448b-8ecb-0e4b795b58d6</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">true</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                  <v n="Identifier">"Exclude"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Exclude this element from build"</v>
                </o>
                <v>23bdaa98-72ec-41f7-817b-9dede5697086</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                  <v n="Identifier">"Parallel"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Sets the branch to parallel mode"</v>
                </o>
                <v>38391c6d-6d4a-42f8-8ee7-9f45e5adafa8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                  <v n="Identifier">"Name"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Name of the element"</v>
                </o>
                <v>62e1754b-7629-4e63-9cec-10ae0c536f1f</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                  <v n="Identifier">"Duplication"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Copies the implementation of step actions or transitions with the element. Otherwise, copies the reference to an existing implementation."</v>
                </o>
                <v>6844a48e-46c2-4cc8-a185-a478f3b99cc0</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                  <v n="Identifier">"InitStep"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Sets the step as the initial step"</v>
                </o>
                <v>700a583f-b4d4-43e4-8c14-629c7cd3bec8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                  <v n="Identifier">"MainAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"Name of the action to be called if the step is active"</v>
                </o>
                <v>7d894980-aeea-405c-a0f6-e2b26429c58f</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">true</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                  <v n="Identifier">"Comment"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Comment of the element"</v>
                </o>
                <v>8294df19-5962-4dee-a874-1051dabb0e3e</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                  <v n="Identifier">"Monitoring"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Indicates transition monitoring setting."</v>
                </o>
                <v>a2621e18-7de3-4ea6-ae6d-89e9e0b7befd</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                  <v n="Identifier">"ExitAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"Name of the action to be called if the step is deactivated"</v>
                </o>
                <v>a6b08bd8-b696-47e3-9cbf-7408b61c9ff8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                  <v n="Identifier">"EntryAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"Name of the action to be called if the step is activated"</v>
                </o>
                <v>b693554c-1b01-4a8d-afde-9e3a46f7465d</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                  <v n="Identifier">"MaxTime"</v>
                  <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Description">"Defines the maximal active time for the step"</v>
                </o>
                <v>bc882c11-1e91-4dd8-a6b8-2075724ed18b</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                  <v n="Identifier">"Symbol"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Symbol configuration setting of the element"</v>
                </o>
                <v>cacf1a68-236e-47c2-b7b1-1cf9199718cb</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                  <v n="Identifier">"MinTime"</v>
                  <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Description">"Defines the minimal active time for the step"</v>
                </o>
                <v>e174fc0d-80b0-4a9e-a530-ca239c249a50</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                  <v n="Identifier">"Qualifier"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Qualifier of the action association"</v>
                </o>
              </d2>
              <d2 n="EnumTemplates" ckt="Guid" cvt="EnumValueTemplate">
                <v>6ecff51c-9b8f-4338-aab0-67c2b31b07e9</v>
                <o>
                  <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                  <l n="Values" t="ArrayList" cet="EnumEntry">
                    <o>
                      <v n="Identifier">"None"</v>
                      <v n="Value">0L</v>
                      <v n="Key">"None"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Variable"</v>
                      <v n="Value">1L</v>
                      <v n="Key">"Variable"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Call"</v>
                      <v n="Value">2L</v>
                      <v n="Key">"Call"</v>
                    </o>
                  </l>
                  <v n="BaseType">"INT"</v>
                </o>
                <v>79a4fdd5-c859-4de4-aa8d-c03372c880c2</v>
                <o>
                  <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                  <l n="Values" t="ArrayList" cet="EnumEntry">
                    <o>
                      <v n="Identifier">"Unspecified"</v>
                      <v n="Value">0L</v>
                      <v n="Key">"Unspecified"</v>
                    </o>
                    <o>
                      <v n="Identifier">"None"</v>
                      <v n="Value">1L</v>
                      <v n="Key">"None"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Read"</v>
                      <v n="Value">2L</v>
                      <v n="Key">"Read"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Write"</v>
                      <v n="Value">3L</v>
                      <v n="Key">"Write"</v>
                    </o>
                    <o>
                      <v n="Identifier">"ReadWrite"</v>
                      <v n="Value">4L</v>
                      <v n="Key">"ReadWrite"</v>
                    </o>
                  </l>
                  <v n="BaseType">"INT"</v>
                </o>
              </d2>
              <v n="ImplId">9L</v>
            </o>
          </Data>
          <TypeList>
            <Type n="ArrayList">System.Collections.ArrayList</Type>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoolValue">{89e1c7bb-c9f8-4be3-b8a7-019cdbb9f7e8}</Type>
            <Type n="EnumEntry">{4185e6da-1717-44c9-b705-102861764479}</Type>
            <Type n="EnumValueTemplate">{d6bfe4f0-d62f-4b5f-9f95-2bbeb1950e28}</Type>
            <Type n="Guid">System.Guid</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="SFCAttribute">{21f3f16e-04fa-4637-b6b7-d84e4192e99f}</Type>
            <Type n="SFCAttributeCategory">{679adacf-f2a4-4167-a3f7-d21cfc5d451f}</Type>
            <Type n="SFCAttributeDescription">{d851789d-af2c-4990-9d48-a7bdc9181773}</Type>
            <Type n="SFCElementList">{587d6556-cfe6-4e76-9cc9-fc0daf0c8c29}</Type>
            <Type n="SFCImplementationObject">{74f81948-1328-492c-b6c1-a9ea72048b28}</Type>
            <Type n="SFCSegment">{f1db7f6f-4774-46a6-ad9b-a94414f875fc}</Type>
            <Type n="String">System.String</Type>
            <Type n="StringValue">{778c8bac-3fa0-41e1-99d3-2b628d12d3e5}</Type>
          </TypeList>
        </XmlArchive>
      </SFC>
    </Implementation>
    <Folder Name="Internal" Id="{20bd2501-e1eb-4995-8337-668ddeba1c4c}" />
    <Folder Name="Public" Id="{242a8bf6-3dc5-446b-a89d-936e418b8756}" />
    <Folder Name="StateControl" Id="{31a6bbdd-3ba2-4185-a10e-7900c7f6f8d3}" />
    <Method Name="ActivateSkill" Id="{d8fc5668-9fa7-43c2-a944-aada2bd4cb8c}" FolderPath="Public\">
      <Declaration><![CDATA[{attribute 'TcRpcEnable':='1'}
METHOD ActivateSkill
VAR_INPUT
// 	pSkill : POINTER TO FB_SKILL;
// 	name: STRING := '';
END_VAR

VAR
	toolready: BOOL;
	i: INT;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[Start();
_owner^.ActivSkill:= THIS;


// IF name<>'' THEN
// 	FOR i := TO_INT(LOWER_BOUND(_owner^.pA_Skills, 1)) TO TO_INT(UPPER_BOUND(_owner^.pA_Skills, 1)) DO
// 		IF _owner^.pA_Skills[i]<>0 THEN
// 			IF FIND(STR1:=pA_Skills[i]^.Name, STR2:=name)<>0 THEN
// 				pSkill:=_owner^.pA_Skills[i];
// 				ADSLOGSTR(
// 					msgCtrlMask := ADSLOG_MSGTYPE_HINT,
// 					msgFmtStr   := 'CallSkill: Found by name: %s',
// 					strArg      := _owner^.pA_Skills[i]^.Name
// 				);
// 				EXIT;
// 			END_IF
// 		END_IF
// 	END_FOR
// 	
// END_IF
// 
// 
// IF pSkill<>0 THEN
// 	activSkill:= pSkill;
// 	
// // 	toolready:=TRUE;
// // 	IF _owner^.pTool<>0 THEN
// // 		toolready:=FALSE;
// // 		IF _owner^.pTool^.State = eState.Active THEN
// // 			toolready:=TRUE;
// // 		END_IF
// // 	END_IF
// 	
// 	
// 	pSkill^.Start();
// ELSE
// 	ADSLOGSTR(
//     msgCtrlMask := ADSLOG_MSGTYPE_ERROR,
//     msgFmtStr   := 'CallSkill: Pointer to Skill is empty: %s',
//     strArg      := _owner^.Path
// );
// END_IF
]]></ST>
      </Implementation>
    </Method>
    <Property Name="Busy" Id="{59c0b902-0e96-4aa6-80c4-17e0cd6c8a94}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Busy : BOOL
]]></Declaration>
      <Get Name="Get" Id="{f0fed57d-7011-4c26-a36d-51ead2ced228}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IF eStatus=eState.Active THEN
	Busy:=TRUE;
ELSE
	Busy:=FALSE;
END_IF]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="DeactivateSkill" Id="{10338084-d473-478a-aa27-fc35b9873599}" FolderPath="Public\">
      <Declaration><![CDATA[{attribute 'TcRpcEnable':='1'}
METHOD DeactivateSkill : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[Stop();
_owner^.ActivSkill:= 0;]]></ST>
      </Implementation>
    </Method>
    <Property Name="Done" Id="{d7794fd0-d52a-411f-ae53-4abe695b2781}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Done : BOOL
]]></Declaration>
      <Get Name="Get" Id="{a38fbf64-c78a-4e85-9631-248ee16d04de}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Done:=bDone;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="onActivate" Id="{ecc4deb5-0154-49af-a556-dd604d8dfee8}" FolderPath="StateControl\">
      <Declaration><![CDATA[METHOD PROTECTED onActivate : eResult

]]></Declaration>
      <Implementation>
        <ST><![CDATA[onActivate := eResult.SUCCESS;
      RETURN;
      // ---- Init ----
_transitionresult:=eResult.None;



// ---- Change ----




// ---- Check ----
_transitionresult := eResult.SUCCESS;


// ---- Change State ----
IF _transitionresult= eResult.SUCCESS THEN
	State:=eState.Active;
ELSIF _transitionresult= eResult.FAILURE THEN
	State:=eState.Inactive;
ELSIF _transitionresult= eResult.ERROR THEN
	State:=eState.ErrorProcessing;
ELSE
	ADSLOGSTR(ADSLOG_MSGTYPE_WARN,'Transitionresult from onActivate is None','');
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="onCleanup" Id="{39f97e2b-ba11-4e41-adb8-2fa35d8f889b}" FolderPath="StateControl\">
      <Declaration><![CDATA[METHOD PROTECTED onCleanup : eResult
]]></Declaration>
      <Implementation>
        <ST><![CDATA[onCleanup := eResult.SUCCESS;
      RETURN;
      // ---- Init ----
_transitionresult:=eResult.None;



// ---- Change ----



// ---- Check ----
_transitionresult := eResult.SUCCESS;


// ---- Change State ----
IF _transitionresult= eResult.SUCCESS THEN
	State:=eState.Unconfigured;
ELSIF _transitionresult= eResult.FAILURE THEN
	ADSLOGSTR(ADSLOG_MSGTYPE_WARN,'Transitionresult from onCleanup is FAILURE ','');
ELSIF _transitionresult= eResult.ERROR THEN
	State:=eState.ErrorProcessing;
ELSE
	ADSLOGSTR(ADSLOG_MSGTYPE_WARN,'Transitionresult from onCleanup is NONE','');
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="onConfigure" Id="{017eb5d1-e54b-4d70-a6cb-15146fd5331d}" FolderPath="StateControl\">
      <Declaration><![CDATA[METHOD PROTECTED onConfigure : eResult
]]></Declaration>
      <Implementation>
        <ST><![CDATA[onConfigure := eResult.SUCCESS;
      RETURN;
      // ---- Init ----
_transitionresult:=eResult.None;



// ---- Change ----


// ---- Check ----
_transitionresult := eResult.SUCCESS;


// ---- Change State ----
IF _transitionresult= eResult.SUCCESS THEN
	State:=eState.Inactive;
ELSIF _transitionresult= eResult.FAILURE THEN
	State:=eState.Unconfigured;
ELSIF _transitionresult= eResult.ERROR THEN
	State:=eState.ErrorProcessing;
ELSE
	ADSLOGSTR(ADSLOG_MSGTYPE_WARN,'Transitionresult from onConfigure is None','');
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="onDeactivate" Id="{0937e09f-333a-4e3a-844b-9f0a153fa24d}" FolderPath="StateControl\">
      <Declaration><![CDATA[METHOD PROTECTED onDeactivate : eResult
]]></Declaration>
      <Implementation>
        <ST><![CDATA[onDeactivate := eResult.SUCCESS;
      RETURN;
      // ---- Init ----
_transitionresult:=eResult.None;



// ---- Change ----
 //Stopping SFC



// ---- Check ----
_transitionresult := eResult.SUCCESS;


// ---- Change State ----
IF _transitionresult= eResult.SUCCESS THEN
	State:=eState.Inactive;
ELSIF _transitionresult= eResult.FAILURE THEN
	ADSLOGSTR(ADSLOG_MSGTYPE_WARN,'Transitionresult from onDeactivate is FAILURE','');
ELSIF _transitionresult= eResult.ERROR THEN
	State:=eState.ErrorProcessing;
ELSE
	ADSLOGSTR(ADSLOG_MSGTYPE_WARN,'Transitionresult from onDeactivate is None','');
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="onError" Id="{5ea8935e-cd95-4d1d-b64a-37648a2cf45e}" FolderPath="StateControl\">
      <Declaration><![CDATA[METHOD PROTECTED onError : eResult
]]></Declaration>
      <Implementation>
        <ST><![CDATA[onError := eResult.SUCCESS;
      RETURN;
      // ---- Init ----
_transitionresult:=eResult.None;



// ---- Change ----





// ---- Check ----
_transitionresult := eResult.SUCCESS;


// ---- Change State ----
IF _transitionresult= eResult.SUCCESS THEN
	State:=eState.Unconfigured;
ELSIF _transitionresult= eResult.FAILURE THEN
	State:=eState.Finalized;
ELSIF _transitionresult= eResult.ERROR THEN
	ADSLOGSTR(ADSLOG_MSGTYPE_WARN,'Transitionresult from onError is Error','');
ELSE
	ADSLOGSTR(ADSLOG_MSGTYPE_WARN,'Transitionresult from onError is None','');
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="onShutdown" Id="{f185d0d9-18df-4a16-be3c-0516eebae000}" FolderPath="StateControl\">
      <Declaration><![CDATA[METHOD PROTECTED onShutdown : eResult
]]></Declaration>
      <Implementation>
        <ST><![CDATA[onShutdown := eResult.SUCCESS;
      RETURN;
      // ---- Init ----
_transitionresult:=eResult.None;



// ---- Change ----



// ---- Check ----
_transitionresult := eResult.SUCCESS;


// ---- Change State ----
IF _transitionresult= eResult.SUCCESS THEN
	State:=eState.Finalized;
ELSIF _transitionresult= eResult.FAILURE THEN
	ADSLOGSTR(ADSLOG_MSGTYPE_WARN,'Transitionresult from onShutdown is FAILURE','');
ELSIF _transitionresult= eResult.ERROR THEN
	State:=eState.ErrorProcessing;
ELSE
	ADSLOGSTR(ADSLOG_MSGTYPE_WARN,'Transitionresult from onShutdown is None','');
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="Pause" Id="{14cdbcfb-a616-4591-a925-297ff9db8a79}" FolderPath="Internal\">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD INTERNAL Pause : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF eStatus=eState.Active THEN
	SFCPause:=TRUE;
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="Restart" Id="{fd5f86ff-0d6c-49e6-bddb-d9209e3aabfc}" FolderPath="Internal\">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD INTERNAL Restart : BOOL //Stay activ, but restart
]]></Declaration>
      <Implementation>
        <ST><![CDATA[SFCReset:=True;]]></ST>
      </Implementation>
    </Method>
    <Method Name="Resume" Id="{3f8922d2-b958-4616-a24f-75320fdcbb9f}" FolderPath="Internal\">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD INTERNAL Resume : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[SFCPause:=False;]]></ST>
      </Implementation>
    </Method>
    <Method Name="Start" Id="{ccb135ee-6087-41f8-8be8-8d6e596b5080}" FolderPath="Internal\">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD INTERNAL Start : BOOL

VAR
	config_succ: BOOL:=TRUE;
	act_succ: BOOL;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF State = eState.Unconfigured THEN
	config_succ:=FALSE;
	config_succ := Configure();
	ADSLOGSTR(
    msgCtrlMask := ADSLOG_MSGTYPE_HINT,
    msgFmtStr   := 'Autoconfiguring Skill %s because Start was called an State = unconfigured',
    strArg      := Path
);
END_IF
IF config_succ THEN
	act_succ := Activate();
END_IF


IF act_succ THEN 
	Start:=TRUE; 
	ADSLOGSTR(
    msgCtrlMask := ADSLOG_MSGTYPE_HINT,
    msgFmtStr   := 'Starting Skill: %s',
    strArg      := Name
);
 END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="Stop" Id="{4c723123-1adf-4d21-9269-2419097dc023}" FolderPath="Internal\">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD INTERNAL Stop : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF eStatus=eState.Active THEN
	SFCPause:=TRUE;
	super^.Deactivate();
END_IF]]></ST>
      </Implementation>
    </Method>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="SFCProperty">
            <n n="SFCErrorAnalyzation" />
            <n n="SFCErrorAnalyzationTable" />
            <n n="SFCCurrentSteps" />
            <n n="SFCMetaSteps" />
            <v n="Title">"IecSfc"</v>
            <v n="Company">"System"</v>
            <v n="Version">"4.4.0.0"</v>
            <v n="Namespace">""</v>
            <d2 n="Flags" ckt="Flags" cvt="SFCPropertyFlagData">
              <v>EnableLimit</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Init</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Reset</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>QuitError</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Pause</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Error</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Trans</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>ErrorStep</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>ErrorPOU</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>CurrentStep</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Tip</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>TipMode</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>SFCErrorAnalyzation</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>SFCErrorAnalyzationTable</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>CurrentSteps</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
            </d2>
            <v n="CalcActiveTransOnly">true</v>
            <v n="UseDefaults">true</v>
          </o>
        </Data>
        <TypeList>
          <Type n="Boolean">System.Boolean</Type>
          <Type n="Flags">{27d8150b-ef58-4fff-8da1-1f7dd5f9ea51}</Type>
          <Type n="SFCProperty">{58548d2c-f1b1-453d-9195-66c94e2a3ae0}</Type>
          <Type n="SFCPropertyFlagData">{24565a38-6368-4874-ab9a-0ef7ec269521}</Type>
          <Type n="String">System.String</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
  </POU>
</TcPlcObject>