@startuml
title Robot System Architecture

skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
allowmixing
' ==========================================================
' Base Classes
' ==========================================================

abstract class BaseComponent {
  == Base Props ==
  + name : STRING
  + id : INT
  + state : State
  + transition : InternalTransitions
  + error : Error
  --
  - fb_init()
  + create()
  + cleanup()
  + configure()
  + activate()
  + deactivate()
  + shutdown()
  + destroy()

  - onConfigure()
  - onCleanup()
  - onActivate()
  - onDeactivate()
  - onShutdown()
  - onError()
}

enum State {
  Unconfigured
  Inactive
  Active
  Finalized
  Configuring
  CleaningUp
  Activating
  Deactivating
  ShuttingDown
  ErrorProcessing}

enum SupervisoryTransitions {
  create
  configure
  cleanup
  activate
  deactivate
  shutdown
  destroy
}

enum InternalTransitions {
  Configuring
  CleaningUp
  ShuttingDown
  Activating
  Deactivating
  ErrorProcessing
}


enum Mode {
  Manual
  Automatic
}

BaseComponent -- SupervisoryTransitions
BaseComponent -- InternalTransitions
BaseComponent -- Mode

struct Error {
  + code : INT
  + message : STRING
  + timestamp : DATETIME
  + severity : Severity
}

enum Severity {
  Info
  Warning
  Error
  Critical
}

Error ..> Severity
BaseComponent -- Error

' ==========================================================
' Robot
' ==========================================================



class Robot extends BaseComponent {

  == Robot Props ==
  + ipadress: STRING
  + port: INT

  + mode : Mode

  + moving : BOOL {readonly}
  + standstill : BOOL {readonly}
  + safetyOk : BOOL {readonly}
  --
  + enable()
  + disable()
  + M_Auto()
  + M_Man()
  + stop()
  + enableVelocityOverride()
  + disableVelocityOverride()


  + MC_SetOperationMode
  + MC_ChangeSpeedOverride( factor: REAL)

' MoveL
  + MC_MoveLinearAbsolute(target: Target)
' MoveJ
  + MC_MoveAxesAbsolute(target: Target)
' Jog
  + MC_MoveAxesRelative(axes: List<Axis>, offsets: List<REAL>)

  + MC_ReadActualVelocity() : Pose
  + MC_ReadAnalogInput(input: INT) : REAL
  + MC_ReadDigitalInput(input: INT) : BOOL
  + MC_SetDigitalOutput(output: INT, value: BOOL)

}

BaseComponent o-- Helper : uses


struct 6JointPosition {
  + joint1 : REAL
  + joint2 : REAL
  + joint3 : REAL
  + joint4 : REAL
  + joint5 : REAL
  + joint6 : REAL
}

struct 2JointPosition {
  + left : REAL
  + right : REAL
}

struct Pose {
    x : REAL
    y : REAL
}
struct 2DPose extends Pose {
  + theta : REAL
}
struct 3DPose extends Pose {
  + z : REAL
  + rx : REAL
  + ry : REAL
  + rz : REAL
}


struct Target {
    name : STRING
    frameId : INT
}
struct 3DTarget extends Target {
  + pose : 3DPose
}
struct 2DTarget extends Target {
  + pose : 2DPose
}

3DTarget ..> 3DPose
2DTarget ..> 2DPose



class 6AxisRobot extends Robot {

  == Robot Props ==
  + currentTool : TOOL
  + currentFrame : FRAME
  + currentFrameId : INT
  + jointPosition : 6JointPosition
  + jointVelocity : 6JointPosition
  + TCPPosition : 3DPose
  + TCPVelocity : 3DPose
  + isInHomePosition : BOOL
  + isInCollision : BOOL
  + Cam: Camera
  --
  + Home()
  + SwitchTool(tool : TOOL)


}

6AxisRobot -- 6JointPosition
6AxisRobot -- 3DPose
' ==========================================================
' AMR (Autonomous Mobile Robot)
' ==========================================================

class AMR extends Robot {

  == AMR Props ==
  + jointPosition : 2JointPosition {readonly}
  + jointVelocity : 2JointPosition {readonly}
  + TCPPosition : 2DPose {readonly}
  + TCPVelocity : 2DPose {readonly}
  + currentGoal : 2DTarget {readonly}
  + batteryVoltage : REAL {readonly}
  + batteryLevel : Int {readonly}
  + localizationPrecision : REAL {readonly}
'   + navigationState : NavigationState
  + isDocked : BOOL {readonly}

  --
  + navigateTo(goal : 2DTarget)
  + stopNavigation()
  + dock( dockId : INT)
  + undock()
}

AMR -- 2JointPosition
AMR -- 2DPose
' ==========================================================
' Tool
' ==========================================================

class Tool extends BaseComponent {

  == Tool Props ==
  + opened : BOOL {readonly}
  + closed : BOOL {readonly}
  + partDetected : BOOL {readonly}

  --
  + open()
  + close()
}



' ==========================================================
' Camera
' ==========================================================

abstract class Camera extends BaseComponent {

  == Camera Props ==
  + resolution : Array<INT>
  + frameRate : INT
  + imageFormat : STRING
  + imageWidth : INT
  + imageHeight : INT
  --
'   TODO
  + takeImage() 
  + startStream()  
  + stopStream()
}

class TwinCATCamera {
}

class ROS2Camera {
}

Camera <|-- TwinCATCamera
Camera <|-- ROS2Camera


abstract class Helper {
  + ImportConfigFromFile()
  + SaveConfigToFile()
  + LoadToolConfigFromFile()
  + LoadFrameConfigFromFile()
  + LoadTargetConfigFromFile()
  + SaveToolConfigToFile()
  + SaveFrameConfigToFile()
  + SaveTargetConfigToFile()
}

class TargetManager {
  + AddTarget(target : Target)
  + RemoveTarget(target : Target)
  + UpdateTarget(target : Target)
  + GetTargetByName(name : STRING) : Target
  + GetAllTargets() : List<Target>
}



file "Targets.json" as TargetsJson
file "Frames.json" as FramesJson
file "Tools.json" as ToolsJson

file "Fleet.json" as FleetJson

Helper o-- TargetsJson : uses
Helper o-- FramesJson : uses
Helper o-- ToolsJson : uses

TargetManager o-- TargetsJson : uses
TargetManager o-- FramesJson : uses
TargetManager o-- Helper : uses
' Robot "1" o-- "0..*" Camera : has
' Robot "1" o-- "0..*" Skill : provides

' ==========================================================
' Skills
' ==========================================================



abstract class Skill extends BaseComponent {

  == Skill Props ==
  + usedBaseActions : List<BaseAction>
  --
  + checkAvailability() : BOOL
}


class PickAndPlaceSkill
class PalletizingSkill
class InspectionSkill

Skill "1" *-- "0..*" BaseAction
Skill <|-- PickAndPlaceSkill
Skill <|-- PalletizingSkill
Skill <|-- InspectionSkill

' ==========================================================
' SRCI Base Actions
' ==========================================================


class MoveJ
class MoveL
class MoveC
class Wait
class SetDO
class GetDI

BaseAction <|-- MoveJ
BaseAction <|-- MoveL
BaseAction <|-- MoveC
BaseAction <|-- Wait
BaseAction <|-- SetDO
BaseAction <|-- GetDI


@enduml