<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_ROS2Connector" Id="{6a96c8c7-52cd-4751-affe-1665f30e203a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ROS2Connector EXTENDS FB_Base
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[CYCLIC_BASE();
HeartBeat();]]></ST>
    </Implementation>
    <Method Name="Activate" Id="{4246cd57-a8f1-4e05-80bb-46f1fc323209}">
      <Declaration><![CDATA[{error 'Add method implementation or delete method to use base implementation'}
METHOD Activate : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Cleanup" Id="{c09ff638-6fd3-453b-93c9-c293dde25a61}">
      <Declaration><![CDATA[{error 'Add method implementation or delete method to use base implementation'}
METHOD Cleanup : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Configure" Id="{58e52956-5985-4e99-8dea-09275ea2b32d}">
      <Declaration><![CDATA[{error 'Add method implementation or delete method to use base implementation'}
METHOD Configure : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Deactivate" Id="{9df0ddb3-f8f1-4521-97b6-96f891630978}">
      <Declaration><![CDATA[{error 'Add method implementation or delete method to use base implementation'}
METHOD Deactivate : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Destroy" Id="{37571124-ec1b-4c2d-afdc-8e3d36434ad3}">
      <Declaration><![CDATA[{error 'Add method implementation or delete method to use base implementation'}
METHOD Destroy : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Shutdown" Id="{dbbf2126-71c3-4df2-907f-e50c0a4e32b5}">
      <Declaration><![CDATA[{error 'Add method implementation or delete method to use base implementation'}
METHOD Shutdown : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>