<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="_TODO" Id="{066b45c6-4b88-4e09-8705-6da2621f10ea}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION _TODO : BOOL
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// - ros2: specific check IF available
// - ros2: autoconfigure skill
// - opcua connecotr wrtie failed weil kein specific vorhanden war.
// - eyes skill: wird nie in state finalized gehen
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>